version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "importlib-metadata"
      - dependency-name: "typing-extensions"
      - dependency-name: "six"
      - dependency-name: "future"
      - dependency-name: "packaging"
      - dependency-name: "click"
      - dependency-name: "bravado"
    ignore:
      - dependency-name: "zenml"
      - dependency-name: "mlflow"
      - dependency-name: "tensorflow"
      - dependency-name: "neptune-prophet"
      - dependency-name: "spacy"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
